{
  buildGoApplication,
  pkg-config,
  zlib,
  writeShellScriptBin,
}:

let
  # Delivered through nativeBuildInputs so it lands on PATH only via strictDeps.
  # Running it from preBuild is what genuinely exercises the
  # code-generation-from-a-build-tool path (the go-bindata/make step the heavy
  # minikube fixture covers), kept tiny and deterministic.
  greetingGen = writeShellScriptBin "greeting-gen" ''
    printf 'package main\n\nconst greeting = "hello from codegen"\n' > greeting_gen.go
  '';
in
buildGoApplication {
  pname = "cgo-codegen";
  version = "0.1.0";

  src = ./.;
  pwd = ./.;
  modules = ./gomod2nix.toml; # generated by tests/run.go before nix-build

  CGO_ENABLED = "1"; # the point of the fixture: link a C library via cgo
  doCheck = false;

  nativeBuildInputs = [
    pkg-config
    greetingGen
  ];
  buildInputs = [ zlib ];

  # goBuildHook runs `runHook preBuild` in the writable source root before
  # building; generate the .go file the main package depends on.
  preBuild = "greeting-gen";
}
